export { default as T } from './Translation';
export { default as Image } from './Image';
export { default as Layout } from './Layout';
export { default as SEO } from './SEO'
export { default as Faq } from './Faq'
export { default as HomeWelcome } from './HomeWelcome'
export { default as DienstenHeader } from './DienstenHeader'
export { default as About } from './About'
export { default as Teamleden } from './Teamleden'
export { default as Contact } from './Contact'
export { default as DienstenLijst } from './DienstenLijst'
